FROM python:3.7-stretch
ENV MYSQL_USERNAME='directdevops'
ENV MYSQL_PASSWORD='directdevops'
ENV MYSQL_SERVER='localhost'
ENV MYSQL_SERVER_PORT='3306'
ENV MYSQL_DATABASE='test'
EXPOSE 8080
RUN git clone https://github.com/DevProjectsForDevOps/StudentCoursesRestAPI.git
WORKDIR StudentCoursesRestAPI
RUN pip install -r requirements.txt
ENTRYPOINT ["python","app.py"]



###### Image creation #####
# docker image -t flask:0 .

###### Container creation #########
# docker container run -d -p 8080:8080 -e MYSQL_SERVER=172.17.0.2 --name=flask1 flask:0