---
- hosts: ubuntu
  gather_facts: yes
  become: yes
  roles:
    - commonrole
- hosts: app
  gather_facts: yes
  become: yes
  roles:
    - approle
- hosts: web
  gather_facts: yes
  become: yes
  roles:
    - webrole