---
- hosts:
  gather_facts: yes
  become: yes
  roles:
    - commonrole
- hosts:
  gather_facts: yes
  become: yes
  roles:
    - approle
- hosts:
  gather_facts: yes
  become: yes
  roles:
    - webrole