---
- hosts: ubuntu
  gather_facts: yes
  become: yes
  tasks:
    - name: update all packages
      apt: 
        update_cache: yes
- hosts: nodejs
  gather_facts: yes
  become: yes
  vars:
    folder_path: /home/ansible
    setupVersion: 8.x
    portNumber: 3000
  tasks: 
  - name: download setup.sh
    command: curl -sL https://deb.nodesource.com/setup_"{{setupVersion}}" -o "{{folder_path}}"/nodesource_setup.sh
    args:
      creates: "{{folder_path}}/nodesource_setup.sh"
  - name: run setup.sh
    shell: "/bin/bash {{folder_path}}/nodesource_setup.sh"
  - name: install nodejs
    apt:
      name: nodejs
      state: present
  - name: install build essential
    apt:
      name: build-essential
      state: present
  - name: copy hello.js to remotenode
    template:
      src: hello.js.j2
      dest: "{{folder_path}}/hello.js"
  - name: install pm2 package using npm
    npm:
      name: pm2
      global: yes
      state: latest
  - name: start nodejs
    command: pm2 start "{{folder_path}}"/hello.js
    become: yes
    become_user: ubuntu
- hosts: nginx
  gather_facts: yes
  become: yes
  vars:
    app_DNS_name: "ip-172-31-19-18.us-west-2.compute.internal"
    app_Private_IP_Address: "172.31.19.18"
    app_Port_Number: 3000
    
  tasks:
  - name: install nginx 
    apt:
      name: nginx
      state: present  
  - name: copy nginx conf file 
    template:
      src: nginxconf.j2
      dest: /etc/nginx/sites-available/default
    notify: "restart nginx"
    
  handlers:    
  - name: restart nginx service 
    service: 
      name: nginx
      state: restarted
    listen: "restart nginx"
