---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: azure-managed-disk
  labels:
    app: mysql-db
    ver: "1.0"
spec:
  accessModes: 
     - ReadWriteOnce
  storageClassName: default
  resources: 
    requests:
      storage: 1Gi