---
# tasks file for approle

  - name: download setup.sh
    command: "curl -sL https://deb.nodesource.com/setup_{{setupVersion}} -o {{folder_path}}/nodesource_setup.sh"
    
  - name: run setup.sh
    shell: "/bin/bash {{folder_path}}/nodesource_setup.sh"
  - name: install nodejs
    apt:
      name: nodejs
      state: present
  - name: install build essential
    apt:
      name: build-essential
      state: present
  - name: copy hello.js to remotenode
    template:
      src: templates/hello.js.j2
      dest: "{{folder_path}}/hello.js"
  - name: install pm2 package using npm
    npm:
      name: pm2
      global: yes
      state: latest
  - name: start nodejs
    command: pm2 start "{{folder_path}}"/hello.js
    become: yes
    become_user: ubuntu