---
apiVersion: v1
kind: Service
metadata:
  name: spc-app-svc
  labels: 
    name:  spc-app
    ver: "1.0"
spec:
  type: LoadBalancer
  ports:
    -  port: 8086
       targetPort:  8080
  selector:
    name:  spc-app
    ver: "1.0"
  

