---
# tasks file for webrole

  - name: install nginx 
    apt:
      name: nginx
      state: present  
  - name: copy nginx conf file 
    template:
      src: templates/nginxconf.j2
      dest: /etc/nginx/sites-available/default
    notify: "restart nginx"