---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
  labels: 
    name:  flask-app
    ver: "1.0"
spec:
  type: LoadBalancer
  ports:
    -  port: 8085
       targetPort:  8080
  selector:
    name:  flask-app
    ver: "1.0"
  

