---
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata: 
    name: cusstorageclass
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
  provisioner: kubernetes.io/aws-ebs
  reclaimPolicy: Delete
  allowVolumeExpansion: true
  mountOptions:
    - debug
  volumeBindingMode: Immediate
  parameters:
    type: gp2
    fsType: ext4