---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stetefulset-example
  label:
    name:
    ver:
spec:
  replicas: 1
  selector:
    matchLabels: 
      name:
      ver:
  serviceName:
  template:
    metadata:
      name: testpod
      labels:
        name: test
        version: 1
    spec: 
      containers:
        - 
          image: nginx
          name: nginx-example
  volumeClaimTemplates:
    metadata:
      name: 
      labels:
        name: test
        version: 1
    spec:
      accessModes:
      storageClassName:
   
      