---
apiVersion: v1
kind: Service
metadata:
  name: gol-app-svc
  labels: 
    name:  gol-app
    ver: "1.0"
spec:
  type: LoadBalancer
  ports:
    -  port: 8080
       targetPort:  8080
  selector:
    name:  gol-app
    ver: "1.0"
  

