apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name:  spc-app
      ver: "1.0"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name:  spc-app
        ver: "1.0"
    spec:
      containers:
        -  name: spccontainer
           image: sreedhargo/spc:0
           env:
             - name: MYSQL_DATABASE
               value: 'test'
             - name: MYSQL_USER
               value: 'directdevops'
             - name: MYSQL_PASSWORD 
               value: 'directdevops'
             - name: MYSQL_ROOT_PASSWORD
               value: 'password'
           ports:
              -  hostPort: 8080
                 containerPort: 8080
                 protocol: TCP
      
